### ISSUE TITLE
Resources do not load with custom WP_CONTENT_DIR & WP_CONTENT_URL

### ISSUE THREAD

**Issue by sthern** [shazahm1/Easy-Table-of-Contents#10]
Hello,

My wp-config.php is set the following way:

define( 'WP_CONTENT_DIR', '/home/user/webapps/website_sub_assets/w');
define( 'WP_CONTENT_URL', 'https://assets.website.com/w');

And the issue is that the TOC plugin does not load, from what I see, at least one of its resources. Please see the attached file.

![toc](https://cloud.githubusercontent.com/assets/5723807/14907643/831c26b6-0dd4-11e6-994f-027a3662c2e2.png)

If this is of any help, I've found the following report on the issue with a different WP plugin here:

https://github.com/WebDevStudios/CMB2/issues/27

Thank you!

**Comment by shazahm1** [comment]
@sthern 

Thanks for the bug report. I read thru the comments in WebDevStudios/CMB2#27 but they do not seem to apply. ezTOC already uses `plugin_dir_url()` and does not use any custom paths like CMB2 needs to. I would expect other plugins not to load assets correctly either if `plugin_dir_url()` is not returning the correct URL...

What is the URL of the CSS and JS of `screen.min.css` and `front.min.js` files? Look in the page source. How does that differ from other CSS and JS files?

**Comment by sthern** [comment]
Hello,

Thank you for reply!

Perhaps it would be more effective if I actually mention the name of page. It is the following:

https://vedika.lv/terms-of-use/

Just now, I did the following experiment. I copied the plugin's folder to root WP folder structure location, i.e. to place where it would've resided if I did not tinker with custom locations/subdomains.

Following this, I reloaded the page, and no change occurred—missing icon was still missing.

I then edited wp-config.php, and removed 'WP_CONTENT_DIR' + 'WP_CONTENT_URL' defines—missing icon appeared.

At the moment, I put the defines back, so that the issue can be observed.

**Comment by shazahm1** [comment]
@sthern 

I looked at the page and the source URL/s are being set correctly. This is not a bug with ezTOC but rather a server config issue. See these links for a solution:

 - https://wordpress.org/support/topic/css-fonts-missing-no-access-control-allow-origin-header?replies=16#post-7550867
 - https://wordpress.org/support/topic/css-fonts-missing-no-access-control-allow-origin-header?replies=16#post-7871950

**Comment by sthern** [comment]
Thank you for your time!

Will explore the links you provided.
