### ISSUE TITLE
External link in TOC

### ISSUE THREAD

**Issue by ghost** [shazahm1/Easy-Table-of-Contents#11]
Hello,

I've customized external links so that they have Font Awesome icon to indicate that they are external, and now the TOC plugin has this icon too.

Please see the code that I added and the screenshot.

Thank you

![toc-ext-link](https://cloud.githubusercontent.com/assets/6915858/14984376/fb2ca472-114a-11e6-8650-df6154209cab.png)

The CSS code:

```
a:not( [href*='mysite.com'] ):not( [href^='/'] ):not( [href^='#'] ):not( [href^=mailto] ):after {
    font-family: 'FontAwesome';
    content: " \f08e";
}
```

**Comment by shazahm1** [comment]
I know this is old...

Looking at this thee issue is your CSS selector, not ezTOC. The toggle does not have an href, adjust your CSS selector accordingly.
