### ISSUE TITLE
Shortcode documentation is absent

### ISSUE THREAD

**Issue by arencambre** [shazahm1/Easy-Table-of-Contents#121]
Because I can enable support for a ToC on particular content types but not make the appearance of the ToC automatic, that means there must be a shortcode I can use to cause the ToC to appear.

There are no instructions anywhere on how to do this. At least basic instructions should appear on **https://[your site domain name]/wp-admin/options-general.php?page=table-of-contents**. Comprehensive instructions must be at or linked from https://wordpress.org/plugins/easy-table-of-contents/.

Looking through your code, I see you register a shortcode named **[ez-toc]** here: https://github.com/shazahm1/Easy-Table-of-Contents/blob/47e8c5d003130fe545293e0d21e5921ea3866361/easy-table-of-contents.php#L154

A Google search on `"ez-toc"` affirms that this is not formally documented and is only referenced in some forum messages.

**Comment by shazahm1** [comment]
The shortcode exists only for backward compatibility and not formally supported. instruction, look at the FAQs on the plugin page

- https://wordpress.org/plugins/easy-table-of-contents/#faq
