### ISSUE TITLE
pinned TOC disappears

### ISSUE THREAD

**Issue by szrudi** [shazahm1/Easy-Table-of-Contents#23]
With the new 1.6 version the TOC on my site disappears. When I switch back to 1.5 it works well, you can [check it out in this video](https://drive.google.com/file/d/1eJ5lT-E0hVx-7eb-de1fASgut9umN3Fd/view?usp=sharing). On the first tab it is opened with v1.5 on the second with the v1.6.

btw, thanks for fixing #19 👍

**Comment by shazahm1** [comment]
Hmmm... can you try the fix I just committed in https://github.com/shazahm1/Easy-Table-of-Contents/commit/29f06a9b6a51f295bf821dda16b226a4369128f8

**Comment by szrudi** [comment]
Yes, I've just tried it and it works! thanks

**Comment by shazahm1** [comment]
Great, I'll try to release 1.6.1 tomorrow with this fix.
