### ISSUE TITLE
Theme Conflict: Avada

### ISSUE THREAD

**Issue by shazahm1** [shazahm1/Easy-Table-of-Contents#28]
@link https://wordpress.org/support/topic/problem-225/
@link https://wordpress.org/support/topic/problem-with-visual-composer-6/#post-9940673
@link https://wordpress.org/support/topic/plugin-vs-avada-theme/

Refactor JS to not depend on WayPoints and then provide widget option to enable/disable the feature. Auto disable the feature and block it so it can not be enabled if Avada is detected.

**Comment by MacLukBal** [comment]
Hey there, 

is there any solution for this issue? By using the eTOC-Plugin all Avada Animations aren´t working...

**Comment by shazahm1** [comment]
@MacLukBal 

As of right now... just this:

https://wordpress.org/support/topic/problem-with-visual-composer-6/page/2/#post-9966567

**Comment by shazahm1** [comment]
@MacLukBal 

Yep, for some reason a wp.org forum mod removed all replies and closed the topic to replies this morning saying it was off topic :/

Any way the post I linked to had this code that another user said worked for them. Add it to you site by using the Code Snippets plugin.

```php
function remove_ezTOC_waypoints() {
    if ( 1 >= did_action('vc_plugins_loaded') ) wp_deregister_script( 'jquery-waypoints' );
}

add_action( 'wp_enqueue_scripts', 'remove_ezTOC_waypoints', 9999 );
```

**Comment by MacLukBal** [comment]
@shazahm1 

Hey! 
First, thanks for your help! 
Unfortunately, the code does not work for Avada. All animations are not loaded. Is there another possibility? 
Thanks you!

**Comment by shazahm1** [comment]
@MacLukBal 

At this point, this is all I have... provided by another Avada user. At this point there is not much I can do for two reasons.

 1. I do not own an Avada license so I can not duplicate and workaround this, the next item...
 2. When I initially investigated this I determined they are including and using a very old version of the Waypoints library. They need to update that library on their end. Perhaps after they do, there will be no more conflict.

At this time I'm not planning on delving too deep into this because I use the widget on my site which uses the Waypoints library and I do not want to break it for myself.

If I can get access to Avada that could help a lot in getting this resolved sooner than later.

**Comment by shazahm1** [comment]
Waypoints has been removed in ca583fe0b9734bc2b48493ffb7d891f5fd84a42d. Closing issue.
