### ISSUE TITLE
Apostrophe / Single quote use in Alternate Header Option

### ISSUE THREAD

**Issue by shazahm1** [shazahm1/Easy-Table-of-Contents#32]
In the alternate header option apostrophe / single quote will be HTML encoded. This should not occur.

ref:
https://wordpress.org/support/topic/alternative-header-function-and-apostrophe-single-quote/

**Comment by Mte90** [comment]
Removing `esc_textarea` on https://github.com/shazahm1/Easy-Table-of-Contents/blob/master/includes/class.admin.php#L262 the problem disappear but require a text change and a new save.

**Comment by Mte90** [comment]
removing that escape is not enough as I can see, if the original term contain an apostrophe there isn't a replace. I am investigating about it.

**Comment by Mte90** [comment]
I made a pr that fix in my case without remove the escape on the textarea.
I added a replace for `'` because `html_entity_decode` seems that change the apostrophe with the another one `.

**Comment by shazahm1** [comment]
Thanks for the PR! I'll review and merge if accepted in the next update.

**Comment by shazahm1** [comment]
I believe I tracked down this issue. It seems I was double escaping the values output to the alt headers and exclude headers. Removing the double escaping seems to have resolved this. After the next update, if you find that this has not been resolved, please reopen.
