### ISSUE TITLE
Target-IDs not created

### ISSUE THREAD

**Issue by Pintolus** [shazahm1/Easy-Table-of-Contents#42]
When the TOC-Widget ist called by shortcode [ez-toc] within my template (sidebar), the anchor links wont work since the corresponding Target-IDs are not added to content. 

You can check here: https://www.hardwaredealz.com/100-euro-bis-200e-gaming-pc-zusammenstellen-zusammenbauen/

**Comment by Pintolus** [comment]
Bug only occurs with the shortcode. If i use the normal widget, the target-IDs are generated.

**Comment by Pintolus** [comment]
Switched to the Widget now instead, which creates the target-IDs. But the active class / highlighter doesnt work properly

**Comment by Pintolus** [comment]
fixed it :)

**Comment by shazahm1** [comment]
Were you trying to use the shortcode within a text widget? If you were, yeah, that would not work.

**Comment by nagro** [comment]
> fixed it :)

how?
