### ISSUE TITLE
TOC sometimes doesn't show

### ISSUE THREAD

**Issue by nmoinvaz** [shazahm1/Easy-Table-of-Contents#44]
I have a theme where the the post contents is loaded dynamically through AJAX. 

With the following line it has problems as it always returns an empty $post even though it should work.

https://github.com/shazahm1/Easy-Table-of-Contents/blob/3afdb23541bad2740aa9879023592ab34a5f2b0e/easy-table-of-contents.php#L423

When I change it to use get_post() it works fine.

**Comment by shazahm1** [comment]
I'll change it to `get_post()`. Pushing the change now.

**Comment by nmoinvaz** [comment]
Thanks!
