### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by shazahm1** [shazahm1/Easy-Table-of-Contents#54]
@link https://github.com/shazahm1/Easy-Table-of-Contents/issues/13#issuecomment-409236182

**Comment by shazahm1** [comment]
tagging @okainov

**Comment by shazahm1** [comment]
@okainov

Can you please reply back with the entire error message. I know which file but not what line the error starts. This will help me track down and correct the cause.

**Comment by okainov** [comment]
@shazahm1  Full error I see:

```
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-includes/post-template.php on line 284

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/post-template.php:284) in /var/www/html/wp-admin/post.php on line 198

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/post-template.php:284) in /var/www/html/wp-includes/pluggable.php on line 1219
```

Also it's weird because on the error page I see the top arrow coming from "WPFront Scroll Top" plugin.

**Comment by okainov** [comment]
@shazahm1 Why is it closed? Was it fixed?

**Comment by shazahm1** [comment]
In as far as I can tell, looking at the error messages shown above, this is not related to ezTOC. And efforts to duplicate in my testing environment, when saving posts, do not generate any errors. 

If you only received this error when ezTOC was activated, I suggest pulling down the master branch again and give it a try as it has changed quite a bit since this issue was opened.
