### ISSUE TITLE
Share\Like buttons from Jetpack plugin are in TOC

### ISSUE THREAD

**Issue by okainov** [shazahm1/Easy-Table-of-Contents#56]
1. Install Jetpack plugin
2. Enable "Share" and "Like" buttons
3. Check some post with TOC and those buttons
4. Make sure they are included in TOC

Since Jetpack is pretty popular plugin, I would expect that its headings should be pre-included into "ignore headings for toc" option.

**Comment by shazahm1** [comment]
Really! Jetpack uses heading for those buttons??? Sounds like bad design to me.

**Comment by marium0505** [comment]
I've simply added the respective headings to the excluded headings, but it would be nice if this was implemented directly into the plugin. You could, eventually, add options to let us decide if Jetpack's Like, Share and related posts (which is also included in the TOC) is to be included in the toc).
