### ISSUE TITLE
Amazon Associates Link Builder

### ISSUE THREAD

**Issue by shazahm1** [shazahm1/Easy-Table-of-Contents#59]
Settings will not save with Amazon Associates Link Builder is active.

@link https://wordpress.org/support/topic/toc-with-link-builder/
@link https://wordpress.org/support/topic/issue-with-amazon-associates-link-builder

**Comment by willstocks-tech** [comment]
I believe AALB is effectively end of life now. There are major issues/incompatibilites and Amazon appear to no longer be supporting it as a plugin 😞 
I've been looking for support for months (there are major performance and compatibility issues with the latest releases) and haven't heard anything for 4+ months [see here](https://wordpress.org/support/topic/can-you-confirm-abandonment-status-of-the-plugin/)

**Comment by shazahm1** [comment]
AALB has officially been pulled from the WP plugin repo and is no longer supported. It appears a similar third party plugin has added backward compatibility to their plugin which suggest it offers a seamless switch. Here's the link:

https://wordpress.org/plugins/amazon-auto-links/

Good luck!
