### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Skullmonkey** [shazahm1/Easy-Table-of-Contents#64]
Hello,

I am trying out this plugin coming from ToC+ and had a couple of questions.

Is there a way that we can define the styles used? I am trying to make the widget floating using Foundation in my sidebar but am unable to find a way to add the necessary components to do so. ( https://foundation.zurb.com/sites/docs/sticky.html )

I see in the readme that there is supposed to be developer documentation but am unable to find it anywhere. Could you point me in the right direction as to where that documentation is?

Thanks

**Comment by shazahm1** [comment]
**RE: Is there a way that we can define the styles used?**

On the Settings : Table of Contents admin page there is an appearance section which has the support style options. You, of course, use CSS to override any of the styles manually as ezTOC has many `id` and `class` selectors available.

**RE: I am trying to make the widget floating using Foundation in my sidebar but am unable to find a way to add the necessary components to do so.**

The is already built in support to make the widget sticky. The option can be found on the Settings : Table of Contents admin page.

You can likely use Foundation also, if you wish. If I remember correctly the is an action run before and after the widget display, so, you could hook into both to wrap the widget in a Foundation sticky container.

**RE: I see in the readme that there is supposed to be developer documentation but am unable to find it anywhere. Could you point me in the right direction as to where that documentation is?**

Are you referring to this statement?

"*Developer friendly with many action hooks and filters available.*"

If you open the plugin in a code editor such as Sublime Text or VSCode you can search for `apply_filters` and `do_action`

**Comment by Skullmonkey** [comment]
It would probably help the users if the "Widget Affix Selector" description could be clarified. The current description says:
```
To enable the option to affix or pin the Table of Contents widget enter the theme's sidebar class or id.
Since every theme is different, this can not be determined automatically. If you are unsure how to find the sidebar's class or id, please ask the theme's support persons.
Eg: .widget-area or #sidebar
```

This is suggesting that we need the class or ID for the entire sidebar instead of needing the class or ID of the widget itself. In my case, instead of putting `#sidebar1` as the option to have the widget float while scrolling, I needed to provide the widget ID `#ezw_tco-2` to obtain that function.

**Comment by shazahm1** [comment]
The instructions are correct for the sticky widget feature.
