### ISSUE TITLE
"Display Hierarchy" option does not apply to widget.

### ISSUE THREAD

**Issue by Skullmonkey** [shazahm1/Easy-Table-of-Contents#65]
When I have the "Display Hierarchy" option checked in the general settings, it works fine for auto inserted posts but the widget does not honor the setting.

See the following image for an example as this is on my local development setup: https://imgur.com/a/VvS8TMv

I like how this worked with ToC+ that had classes of "toc_depth_#" to where I could control the depth of indentation via CSS.

**Comment by shazahm1** [comment]
It is not required to class the TOC item depth to control the depth of indentation. This can be accomplished using CSS and the currently provided el/classes.
