### ISSUE TITLE
Counter setting is not honored

### ISSUE THREAD

**Issue by Skullmonkey** [shazahm1/Easy-Table-of-Contents#66]
Correct me if I am wrong, but I believe that the counter setting would display the following for the numeric and roman numeral settings:

Numeric
```
1: Intro
  1.1: Hello
  1.2: World
2: Guide
  2.1: How
  2.2: Are
  2.3: You
```

Roman Numeral:
```
I: Intro
  I.I: Hello
  I.II: World
II: Guide
  II.I: How
  II.II: Are
  II.III: You
```

No matter what setting I select, I get a bulleted list in the auto inserted ToC but nothing in the widget.

**Comment by shazahm1** [comment]
Check the theme, it is possible that it, or another plugin, is overriding the list styles in ezTOC.
