### ISSUE TITLE
Alternate Headings with '/' won't work.

### ISSUE THREAD

**Issue by yanglongji** [shazahm1/Easy-Table-of-Contents#75]
line:759

`$original_heading = str_replace(
										array( '\*' ),
										array( '.*' ),
										trim( $original_heading )
									);`

should be changed to:

`$original_heading = str_replace(
										array( '\*', '/' ),
										array( '.*', '\/' ),
										trim( $original_heading )
									);`

**Comment by yanglongji** [comment]
line: 800
`$title = strip_tags( apply_filters( 'ez_toc_title', $matches[ $i ][0] ), apply_filters( 'ez_toc_title_allowable_tags', '' )`
should be:
`$title = strip_tags( apply_filters( 'ez_toc_title', $toc[ $i ][0] ), apply_filters( 'ez_toc_title_allowable_tags', '' )`

**Comment by Mte90** [comment]
I added the first comment on https://github.com/shazahm1/Easy-Table-of-Contents/pull/69 because I cannot understand what is the file of the second comment.
