### ISSUE TITLE
ez-toc-title-toggle icon missing

### ISSUE THREAD

**Issue by willstocks** [shazahm1/Easy-Table-of-Contents#77]
Hi guys,

I have just installed ez-toc and have noticed that the glyphicon that is supposed to show next to the title is actually missing.

You can see this on any post on my site – https://willstocks.co.uk

**Comment by willstocks-tech** [comment]
Also posted on [WordPress Support Forum](https://wordpress.org/support/topic/ez-toc-title-toggle-icon-missing/) just for reference 😃

**Comment by shazahm1** [comment]
Closing, can not duplicate. I suspect conflict with theme or another plugin.
